// Escribe todas las historias directamente en disco
const fs = require('fs');
const path = require('path');

const DIR = path.join(__dirname, 'proyectos', 'sge', 'backlog');

const stories = [
  // Sprint 1
  { id: 'SGE-1.1', title: 'Esquema BD PostgreSQL/PostGIS', priority: 'Must', sp: 8, status: 'Done', assignee: 'JOS', sprint: 1, story: 'BD PostgreSQL/PostGIS diseñada e implementada con tablas, índices geoespaciales y seed data.', subtasks: ['Modelo ER completo', 'BD PostgreSQL con PostGIS', 'Índices geoespaciales GIST', 'Migraciones EF Core', 'Seed Data'], ac: ['BD funcional con PostGIS', 'Migraciones sin errores', 'Seed data insertada correctamente'], deps: [] },
  { id: 'SGE-1.2', title: 'Config. proyecto ASP.NET Core y arquitectura base', priority: 'Must', sp: 5, status: 'Done', assignee: 'GER', sprint: 1, story: 'Proyecto .NET configurado con dependencias, middleware y estructura de carpetas.', subtasks: ['Proyecto .NET 9', 'Paquetes NuGet: EF Core, Npgsql, JWT, Swagger', 'Configuración Program.cs', 'DbContext con NetTopologySuite', 'CORS configurado'], ac: ['Proyecto compila y ejecuta', 'Swagger accesible en /swagger'], deps: [] },
  { id: 'SGE-1.3', title: 'Sistema de autenticación y autorización JWT', priority: 'Must', sp: 8, status: 'Done', assignee: 'GER', sprint: 1, story: 'Auth JWT implementado con login, roles y middleware de autorización.', subtasks: ['AuthController: POST /api/auth/login', 'Tokens JWT con claims', 'Políticas de autorización por rol', 'Hash de contraseñas con SHA256', 'DTOs de autenticación', 'Middleware de validación'], ac: ['Login retorna token JWT válido', 'Contraseñas hasheadas', 'Roles Admin y Empleado diferenciados', '401 para peticiones sin token'], deps: ['SGE-1.1','SGE-1.2'] },
  { id: 'SGE-1.4', title: 'Infraestructura Cloud y entorno de desarrollo', priority: 'Must', sp: 5, status: 'Done', assignee: 'JOS', sprint: 1, story: 'Infraestructura cloud configurada con BD PostgreSQL remota y entorno de staging.', subtasks: ['Instancia PostgreSQL cloud', 'PostGIS habilitado', 'Variables de entorno', 'Firewall y seguridad', 'Backups automáticos'], ac: ['BD cloud accesible', 'Backups automáticos funcionando'], deps: ['SGE-1.1'] },
  { id: 'SGE-1.5', title: 'CRUD completo de Empleados (Controller + DTOs)', priority: 'Must', sp: 5, status: 'Done', assignee: 'GER', sprint: 1, story: 'CRUD de empleados implementado con todos los endpoints y validaciones.', subtasks: ['Modelo Empleado completo', 'DTOs de creación/actualización/respuesta', 'EmpleadosController: GET, POST, PUT, PATCH', 'Validaciones con DataAnnotations', 'Manejo de errores HTTP estandarizado'], ac: ['5 endpoints CRUD funcionales', 'Solo Admin puede crear/eliminar', 'Validaciones rechazan datos inválidos'], deps: ['SGE-1.1','SGE-1.2','SGE-1.3'] },
  { id: 'SGE-1.6', title: 'CRUD Lugares de Trabajo con PostGIS', priority: 'Must', sp: 5, status: 'Done', assignee: 'JOS', sprint: 1, story: 'CRUD de lugares con PostGIS implementado, incluyendo geocercas y consultas de proximidad.', subtasks: ['Modelo LugarTrabajo con datos geoespaciales', 'DTOs con conversión de coordenadas', 'LugaresController CRUD', 'ST_DWithin para verificar geocerca', 'Búsqueda por proximidad'], ac: ['Lugares con datos geoespaciales válidos', 'ST_DWithin funcional', 'Búsqueda por proximidad operativa'], deps: ['SGE-1.1','SGE-1.3'] },
  { id: 'SGE-1.7', title: 'Registro de Ubicaciones en tiempo real', priority: 'Must', sp: 5, status: 'Done', assignee: 'GER', sprint: 1, story: 'Endpoint de ubicaciones implementado con almacenamiento geoespacial y consultas en tiempo real.', subtasks: ['Modelo Ubicacion con coordenadas', 'UbicacionesController: POST, GET /ultimas, GET /empleado/{id}', 'Almacenamiento con NetTopologySuite', 'Validaciones de coordenadas y autenticación', 'DTOs de ubicación'], ac: ['Ubicaciones registradas con datos geoespaciales', 'Historial consultable por fecha', 'Última ubicación en menos de 200ms'], deps: ['SGE-1.1','SGE-1.3','SGE-1.6'] },

  // Sprint 2
  { id: 'SGE-2.1', title: 'Integración Vue con API de Autenticación (JWT Interceptor)', priority: 'Must', sp: 5, status: 'Done', assignee: 'ETH', sprint: 2, story: 'Login desde Vue con JWT automático en todas las peticiones.', subtasks: ['Configurar Axios con interceptors para adjuntar JWT Bearer token', 'Implementar Pinia store de autenticación (login, logout, refresh token)', 'Almacenar token en localStorage y restaurar al recargar página', 'Implementar redirect a login si token expira (401 interceptor)'], ac: ['Login funciona con credenciales reales de la BD', 'Token se almacena y reenvía en cada petición', 'Si expira el token, redirige al login automáticamente', 'Logout limpia token y redirige'], deps: ['SGE-1.3'] },
  { id: 'SGE-2.2', title: 'Dashboard Vue con datos reales de la API', priority: 'Must', sp: 5, status: 'Done', assignee: 'ETH', sprint: 2, story: 'Dashboard con datos reales desde la API para monitorear el estado del personal.', subtasks: ['Conectar Dashboard.vue con GET /api/admin/dashboard/estadisticas', 'Mostrar tarjetas con total empleados, en geocerca, fuera de geocerca, alertas hoy', 'Implementar tabla de últimas alertas con datos reales', 'Agregar indicadores de carga (skeleton loaders)', 'Implementar refresh manual y automático cada 30 segundos'], ac: ['Dashboard muestra datos reales de la BD', 'Indicadores de carga visibles mientras se obtienen datos', 'Actualización automática cada 30s', 'Manejo de errores si la API no responde'], deps: ['SGE-1.7','SGE-2.1'] },
  { id: 'SGE-2.3', title: 'CRUD Empleados en Vue conectado a API real', priority: 'Must', sp: 5, status: 'Done', assignee: 'ETH', sprint: 2, story: 'Gestión de empleados desde Vue con datos reales contra la API.', subtasks: ['Conectar lista de Empleados.vue con GET /api/admin/empleados', 'Implementar creación con POST /api/admin/empleados', 'Implementar edición con PUT /api/admin/empleados/{id}', 'Implementar toggle activo con PATCH /api/admin/empleados/{id}/estadoemp', 'Conectar cambio de lugar con PATCH /api/admin/empleados/{id}/lugar-trabajo', 'Agregar búsqueda y filtros'], ac: ['Lista de empleados refleja datos reales de la BD', 'CRUD completo funcional', 'Cambio de lugar se refleja en tiempo real', 'Búsqueda por nombre y CI funcional'], deps: ['SGE-1.5','SGE-2.1'] },
  { id: 'SGE-2.4', title: 'App Flutter: Login + Servicios API + Provider State', priority: 'Must', sp: 8, status: 'Done', assignee: 'ALA', sprint: 2, story: 'Login móvil con Flutter, JWT y Provider para gestión de estado global.', subtasks: ['Scaffold proyecto Flutter con organización de carpetas', 'Configurar tema global (colores SGE: #1A5276, #FF6B00)', 'Implementar AuthService: POST /api/auth/login con almacenamiento local', 'Implementar ApiService singleton con JWT interceptor', 'Configurar Provider para estado global de autenticación', 'Diseñar pantalla de Login con validación de formulario', 'Implementar AuthGate: redirección automática'], ac: ['Login funcional contra API real', 'Token se almacena en SharedPreferences', 'Al cerrar y abrir la app, mantiene sesión activa', 'Provider actualiza el estado correctamente'], deps: ['SGE-1.3'] },
  { id: 'SGE-2.5', title: 'Pantalla Reportes en Vue conectada a API', priority: 'Must', sp: 5, status: 'Done', assignee: 'ETH', sprint: 2, story: 'Reportes de asistencia desde Vue con datos reales de la API.', subtasks: ['Conectar Reportes.vue con GET /api/admin/reportes/asistencia?desde=&hasta=', 'Implementar selector de rango de fechas con date picker', 'Mostrar resultados en tabla con paginación', 'Implementar exportación a CSV', 'Agregar filtros por empleado y lugar de trabajo'], ac: ['Reportes se generan con datos reales de la BD', 'Filtros por fecha, empleado y lugar funcionan', 'Exportación a CSV descarga archivo válido', 'Paginación funcional para grandes volúmenes'], deps: ['SGE-2.1'] },
  { id: 'SGE-2.6', title: 'Pantalla Lugares en Vue con mapa y geocercas', priority: 'Must', sp: 5, status: 'Done', assignee: 'ETH', sprint: 2, story: 'Gestión de lugares con Mapbox y geocercas desde Vue.', subtasks: ['Conectar Lugares.vue con GET /api/admin/lugares', 'Implementar mapa con Mapbox mostrando todos los lugares', 'Mostrar geocercas como círculos en el mapa', 'Implementar creación/edición de lugares con coordenadas', 'Implementar eliminación lógica de lugares', 'Mostrar empleados asignados a cada lugar'], ac: ['Lugares se muestran en el mapa con sus geocercas', 'CRUD de lugares funcional contra API real', 'Al crear/editar un lugar, la geocerca se actualiza en el mapa'], deps: ['SGE-1.6','SGE-2.1'] },
  { id: 'SGE-2.7', title: 'Flutter: Dashboard + Login completos', priority: 'Must', sp: 8, status: 'Done', assignee: 'ALA', sprint: 2, story: 'Dashboard y pantallas base de Flutter funcionales.', subtasks: ['Implementar Dashboard screen con tarjetas de estadísticas personales', 'Conectar con GET /api/ubicaciones/mi-dashboard', 'Agregar bottom navigation con tabs', 'Implementar navegación entre pantallas', 'Agregar indicadores de carga y manejo de errores'], ac: ['Dashboard muestra estadísticas personales reales', 'Bottom navigation funcional', 'Navegación fluida entre pantallas'], deps: ['SGE-2.4'] },

  // Sprint 3
  { id: 'SGE-3.1', title: 'Flutter: Pantallas completas (Lugares, Perfil, Historial)', priority: 'Must', sp: 8, status: 'InProgress', assignee: 'ALA', sprint: 3, story: 'Todas las pantallas de la app Flutter completamente funcionales.', subtasks: ['Implementar LugaresScreen: mapa con lugares asignados y geocercas', 'Implementar PerfilScreen: datos personales, cambiar contraseña', 'Implementar HistorialScreen: historial de ubicaciones por fecha', 'Implementar BottomNavigationBar con todas las secciones', 'Navegación fluida entre pantallas'], ac: ['Todas las pantallas navegables sin errores', 'LugaresScreen muestra geocercas en mapa', 'PerfilScreen permite cambio de contraseña', 'HistorialScreen muestra ubicaciones filtradas'], deps: ['SGE-2.4','SGE-2.7'] },
  { id: 'SGE-3.2', title: 'Geolocalización en tiempo real con servicio en segundo plano', priority: 'Must', sp: 8, status: 'InProgress', assignee: 'ALA', sprint: 3, story: 'GPS en segundo plano reportando ubicación a la API sin intervención del usuario.', subtasks: ['Configurar geolocator/geolocation package en Flutter', 'Implementar servicio de localización en foreground', 'Implementar servicio en background con WorkManager (Android)', 'Enviar ubicación a POST /api/ubicaciones cada N segundos', 'Calcular distancia a geocercas localmente', 'Manejar permisos de ubicación (always, while in use)'], ac: ['Ubicación se reporta cada 30s en foreground', 'Ubicación se reporta cada 60s en background', 'App funciona con permisos "While in use" y "Always"', 'Indicador GPS visible en la UI'], deps: ['SGE-1.7','SGE-3.1'] },
  { id: 'SGE-3.3', title: 'Notificaciones push vía Firebase Cloud Messaging', priority: 'Must', sp: 5, status: 'InProgress', assignee: 'ALA', sprint: 3, story: 'Notificaciones push al cruzar geocerca para acción inmediata.', subtasks: ['Configurar proyecto Firebase y descargar google-services.json', 'Integrar firebase_messaging en Flutter', 'Implementar endpoint POST /api/notificaciones/registrar-dispositivo', 'Enviar notificaciones desde el backend al generar alerta', 'Manejar acción al tocar la notificación'], ac: ['Notificación push recibida al cruzar geocerca', 'Al tocar notificación abre el detalle de la alerta', 'Dispositivo registrado correctamente en la API'], deps: ['SGE-1.7','SGE-3.2'] },
  { id: 'SGE-3.4', title: 'Soporte offline: caché local y sincronización', priority: 'Must', sp: 5, status: 'InProgress', assignee: 'ALA', sprint: 3, story: 'App funciona sin conexión con sincronización automática al recuperar señal.', subtasks: ['Implementar base de datos local con sqflite o drift', 'Cachear datos de empleado, lugares y último dashboard', 'Almacenar ubicaciones pendientes de envío en cola local', 'Sincronizar ubicaciones encoladas cuando vuelva la conexión', 'Mostrar indicador de "modo offline" en la UI'], ac: ['App muestra datos cacheados sin conexión', 'Ubicaciones se encolan y envían al reconectar', 'Indicador offline visible', 'Sin pérdida de datos al alternar conexión'], deps: ['SGE-3.1'] },
  { id: 'SGE-3.5', title: 'Flutter: Mapa en vivo con ubicación de empleados', priority: 'Must', sp: 8, status: 'Todo', assignee: 'ALA', sprint: 3, story: 'Mapa en vivo con todas las ubicaciones de empleados desde la app.', subtasks: ['Integrar Mapbox GL o Google Maps en Flutter', 'Obtener ubicaciones con GET /api/ubicaciones/ultimas', 'Mostrar marcadores con colores según estado (dentro/fuera geocerca)', 'Actualizar marcadores en intervalo configurable (15s)', 'Tooltip con datos del empleado al hacer tap'], ac: ['Mapa muestra todos los empleados activos', 'Actualización automática cada 15s', 'Tooltip funcional al tocar marcador'], deps: ['SGE-3.1','SGE-3.2'] },
  { id: 'SGE-3.6', title: 'Flutter: Reportes y vista de detalle por empleado', priority: 'Must', sp: 5, status: 'Todo', assignee: 'ALA', sprint: 3, story: 'Reportes detallados desde la app móvil.', subtasks: ['Implementar ReportesScreen con selector de fechas', 'Conectar GET /api/admin/reportes/asistencia por empleado', 'Mostrar tabla de asistencias con indicador dentro/fuera', 'Vista de detalle por empleado con historial'], ac: ['Reportes por empleado funcionales', 'Selector de fechas operativo', 'Datos históricos visibles y filtrables'], deps: ['SGE-3.1'] },
  { id: 'SGE-3.7', title: 'Vue: Panel administración avanzado + exportación de datos', priority: 'Must', sp: 5, status: 'Todo', assignee: 'ETH', sprint: 3, story: 'Panel avanzado con exportación de datos y filtros potentes.', subtasks: ['Agregar exportación a Excel/PDF en Reportes.vue', 'Implementar filtros combinados (fecha + empleado + lugar)', 'Agregar gráficos de tendencias (Chart.js) en Dashboard', 'Agregar selector de columnas visibles en tablas'], ac: ['Exportación Excel/PDF genera archivos válidos', 'Gráficos de tendencias funcionales', 'Filtros combinados funcionan correctamente'], deps: ['SGE-2.2','SGE-2.3'] },
  { id: 'SGE-3.8', title: 'Optimización de batería y datos en segundo plano', priority: 'Should', sp: 3, status: 'Backlog', assignee: 'ALA', sprint: 3, story: 'Reducir consumo de batería mientras se reporta ubicación en segundo plano.', subtasks: ['Reducir frecuencia de envío a 60-120s en background', 'Implementar debounce: no enviar si ubicación no cambió significativamente', 'Comprimir payloads de ubicación antes de enviar', 'Probar consumo de batería en sesión de 4h'], ac: ['Consumo de batería menor al 15% en 4h de uso', 'Datos móviles usan menos de 50MB en jornada de 8h'], deps: ['SGE-3.2'] },
  { id: 'SGE-3.9', title: 'Internacionalización (i18n) — Multi-idioma', priority: 'Should', sp: 3, status: 'Backlog', assignee: 'ETH', sprint: 3, story: 'Soporte multi-idioma (ES/EN) en la app.', subtasks: ['Configurar i18n en Flutter con flutter_localizations', 'Extraer todos los strings a archivos .arb', 'Implementar selector de idioma en PerfilScreen'], ac: ['App traducible entre ES/EN', 'Selector de idioma funcional', 'Cadenas extraídas correctamente'], deps: ['SGE-3.1'] },
  { id: 'SGE-3.10', title: 'Pruebas de carga con 1000+ ubicaciones simultáneas', priority: 'Could', sp: 3, status: 'Backlog', assignee: 'GER', sprint: 3, story: 'Garantizar escalabilidad del sistema con 1000 empleados simultáneos.', subtasks: ['Crear script de pruebas de carga con k6 o Artillery', 'Simular 1000+ ubicaciones concurrentes', 'Medir tiempo de respuesta promedio', 'Documentar límites y recomendar optimizaciones'], ac: ['API responde en menos de 500ms con 1000 requests/s', 'Documento de capacidad del sistema generado'], deps: ['SGE-1.7','SGE-2.2'] },
  { id: 'SGE-3.11', title: 'Tema oscuro/claro configurable', priority: 'Could', sp: 2, status: 'Backlog', assignee: 'ETH', sprint: 3, story: 'Tema configurable para adaptarse a condiciones de iluminación.', subtasks: ['Implementar ThemeProvider en Flutter', 'Persistir preferencia de tema en SharedPreferences'], ac: ['Tema oscuro/claro funcional', 'Preferencia persiste al recargar'], deps: ['SGE-2.1'] }
];

let count = 0;
stories.forEach(s => {
  const filePath = path.join(DIR, s.id.replace(/\./g, '-') + '.json');
  const data = {
    id: s.id,
    title: s.title,
    priority: s.priority,
    sp: s.sp,
    status: s.status,
    assignee: s.assignee,
    sprint: s.sprint,
    story: s.story,
    subtasks: s.subtasks,
    ac: s.ac,
    deps: s.deps || [],
    created: '2026-05-14T16:07:00.000Z',
    updated: '2026-05-14T16:07:00.000Z'
  };
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
  count++;
});

console.log(`[OK] ${count} historias escritas en disco`);
